import os
import re
import time
import random
import shutil
import zipfile
import xml.etree.ElementTree as ET
from datetime import datetime
from pathlib import Path
# Importations fictives pour la gestion des erreurs de dépendance externe
try:
    from PIL import Image 
    PILLOW_INSTALLED = True
except ImportError:
    Image = None
    PILLOW_INSTALLED = False

try:
    import PyPDF2
    PYPDF2_INSTALLED = True
except ImportError:
    # On utilise un print plus doux pour éviter les erreurs dans le console d'exécution.
    print("[ATTENTION] La librairie PyPDF2 n'est pas installée. Le nettoyage PDF sera désactivé.")
    PYPDF2_INSTALLED = False


class MetadataCleaner:
    """
    Classe de nettoyage anti-détection : 
    1. Supprime les métadonnées (dates, auteurs, etc.).
    2. Retire les marqueurs IA du contenu textuel.
    3. Humanise le texte selon différents styles linguistiques.
    4. Nettoie les métadonnées des fichiers binaires (PDF, Office, Image).
    """
    def __init__(self):
        # Extensions de fichiers gérées
        self.text_extensions = ['.txt', '.md', '.py', '.js', '.html', '.css', '.xml', '.json']
        self.image_extensions = ['.jpg', '.jpeg', '.png', '.gif', '.bmp', '.tiff']
        self.document_extensions = ['.pdf', '.docx', '.xlsx', '.pptx']

    # ------------------------------------------------------------
    #  MÉTHODES DE NETTOYAGE DES FICHIERS (I/O)
    # ------------------------------------------------------------
    def clean_file_metadata(self, file_path: Path) -> bool:
        """Point d'entrée principal pour le nettoyage des métadonnées."""
        print(f"\n[CLEANING] Démarrage du nettoyage de : {file_path}")
        try:
            # Utilisation du chemin absolu (resolve()) pour plus de sécurité.
            safe_path = file_path.resolve() 
            _, ext = os.path.splitext(str(safe_path).lower())
            self._modify_file_dates(safe_path)

            if ext in self.text_extensions:
                self._clean_text_file(safe_path)
            elif ext in self.document_extensions:
                self._clean_document_file(safe_path)
            elif ext in self.image_extensions and PILLOW_INSTALLED:
                self._clean_image_file(safe_path)

            return True
        except Exception as e:
            print(f"[ERREUR] Échec du nettoyage global de {file_path} : {type(e).__name__}: {e}")
            return False

    def _modify_file_dates(self, file_path: Path):
        """Modifie les dates d'accès et de modification."""
        days = random.randint(1, 365)
        hours = random.randint(0, 23)
        minutes = random.randint(0, 59)
        mod = time.time() - (days * 86400) - (hours * 3600) - (minutes * 60)
        create = mod - random.randint(3600, 86400 * 7)
        os.utime(str(file_path), (mod, create))

    def _clean_text_file(self, file_path: Path):
        """Supprime les marqueurs IA et autres traces de génération dans le texte."""
        try:
            with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()

            patterns = [
                r'generated by.*?ai', r'created with.*?ai', r'powered by.*?ai',
                r'using.*?ai', r'ai-generated', r'gpt-\d', r'claude', r'gemini',
                r'bard', r'chatgpt', r'openai', r'anthropic', r'google',
                r'microsoft', r'meta', r'automatically generated',
                r'machine-generated', r'generated on \d{4}-\d{2}-\d{2}',
            ]

            for p in patterns:
                content = re.sub(p, "", content, flags=re.IGNORECASE)

            with open(file_path, "w", encoding="utf-8") as f:
                f.write(content)
        except Exception as e:
             print(f" [ERREUR] Problème de lecture/écriture dans le fichier texte ({file_path}) : {e}")

    def _clean_document_file(self, file_path: Path):
        """Contrôle l'appel au nettoyage PDF ou Office en fonction de l'extension."""
        _, ext = os.path.splitext(str(file_path).lower())
        if ext == ".pdf" and PYPDF2_INSTALLED:
            self._clean_pdf_metadata(file_path)
        elif ext in ['.docx', '.xlsx', '.pptx']:
            self._clean_office_metadata(file_path)
        else:
             print(f" [AVERTISSEMENT] Format de document non géré par le cleaner ({ext}).")

    def _clean_pdf_metadata(self, file_path: Path):
        """Nettoie les métadonnées d'un fichier PDF en réécrivant le contenu."""
        # Création du nom temp sécurisé avec l'extension originale.
        temp = f"{file_path}_temp_{random.randint(100, 999)}.pdf"

        try:
            reader = PyPDF2.PdfReader(str(file_path))
            writer = PyPDF2.PdfWriter()

            for page in reader.pages:
                writer.add_page(page)

            clean_metadata = {k: "" for k in [
                "/Creator", "/Producer", "/Author", "/Title",
                "/Subject", "/Keywords", "/CreationDate", "/ModDate"
            ]}
            writer.add_metadata(clean_metadata)

            with open(temp, "wb") as out:
                writer.write(out)

            shutil.move(temp, str(file_path)) # Remplacement atomique
        except Exception as e:
            print(f" [ERREUR] Échec critique lors du nettoyage PDF : {type(e).__name__}: {e}")
        finally:
             if os.path.exists(temp):
                os.remove(temp)

    def _clean_office_metadata(self, file_path: Path):
        """Nettoie les métadonnées des documents Office (ZIP -> Clean XML -> ZIP)."""
        base = os.path.splitext(file_path)[0]
        temp_dir = f"{base}_temp_{random.randint(1, 999)}" 
        temp_file = f"{base}_temp{os.path.splitext(file_path)[1]}"

        try:
            with zipfile.ZipFile(str(file_path), "r") as z:
                z.extractall(temp_dir)

            for xml_file in ["core.xml", "app.xml"]:
                path = os.path.join(temp_dir, "docProps", xml_file)
                if os.path.exists(path):
                    try:
                        tree = ET.parse(path)
                        root = tree.getroot()
                        for elem in root.iter():
                            elem.text = "" 
                        tree.write(path, encoding="utf-8", xml_declaration=True)
                    except ET.ParseError as e:
                        print(f" [AVERTISSEMENT] Erreur lors de la lecture XML : {e}")

            with zipfile.ZipFile(temp_file, "w") as z:
                for folder, _, files in os.walk(temp_dir):
                    for file in files:
                        fp = os.path.join(folder, file)
                        arc = os.path.relpath(fp, temp_dir)
                        z.write(fp, arc)

            shutil.move(temp_file, str(file_path)) 
        except zipfile.BadZipFile:
             print(" [ERREUR] Le fichier Office n'est pas un format ZIP valide.")
        except Exception as e:
            print(f" [ERREUR] Échec du nettoyage Office : {type(e).__name__}: {e}")
        finally:
            if os.path.exists(temp_dir):
                shutil.rmtree(temp_dir)

    def _clean_image_file(self, file_path: Path):
        """Ré-encode l'image pour perdre les métadonnées EXIF."""
        if not PILLOW_INSTALLED: return
        try:
            img = Image.open(str(file_path))
            data = list(img.getdata())
            # Créer une nouvelle image (méthode anti-EXIF classique)
            img2 = Image.new(img.mode, img.size) 
            img2.putdata(data)
            img2.save(str(file_path)) 
        except Exception as e:
             print(f" [ERREUR] Impossible de nettoyer l'image : {e}")


    # ============================================================
    #  *** MOTEUR ANTI-DÉTECTION — CIBLE CHAQUE DIMENSION ***
    # ============================================================
    #
    # Le détecteur (detecteur.py) calcule 8 dimensions. Ce moteur
    # les attaque toutes chirurgicalement, dans l'ordre de leur poids.
    #
    # Poids des dimensions (total = 1.0) :
    #   Perplexité lex.      0.20  → enrichir le vocabulaire
    #   Marqueurs IA         0.20  → supprimer connecteurs/fillers
    #   Uniformité phrases   0.15  → varier les longueurs (CV)
    #   Richesse ponctuation 0.10  → injecter —, …, !!, ??
    #   Diversité lexicale   0.10  → CTTR : augmenter les hapax
    #   Structures IA        0.10  → supprimer listes/markdown
    #   Burstiness           0.10  → Gini élevé = phrases très inégales
    #   Ton assertif/prudent 0.05  → réduire overconfident+hedging
    #
    # ============================================================

    # ── Listes exactes du détecteur (miroir de detecteur.py) ────

    _DET_AI_MARKERS = re.compile(
        r"\b(tout d'abord|premièrement|deuxièmement|troisièmement|en premier lieu|"
        r"en second lieu|en conclusion|pour conclure|en résumé|en somme|"
        r"il convient de|il est important de|il est essentiel de|"
        r"dans ce contexte|à cet égard|à titre d'exemple|"
        r"firstly|secondly|thirdly|furthermore|moreover|additionally|"
        r"in conclusion|to summarize|it is worth noting|it is important to|"
        r"in this context|in this regard)\b",
        re.IGNORECASE,
    )
    _DET_SMOOTH = re.compile(
        r"\b(de plus|par ailleurs|en outre|cependant|néanmoins|toutefois|"
        r"en revanche|d'une part|d'autre part|quoi qu'il en soit|"
        r"furthermore|however|nevertheless|nonetheless|on the other hand|"
        r"in addition|that being said|with that said)\b",
        re.IGNORECASE,
    )
    _DET_FILLERS = re.compile(
        r"\b(très|vraiment|absolument|totalement|complètement|"
        r"entièrement|particulièrement|notamment|spécifiquement|"
        r"very|really|absolutely|totally|completely|entirely|"
        r"particularly|specifically|essentially|basically)\b",
        re.IGNORECASE,
    )
    _DET_OVERCONFIDENT = re.compile(
        r"\b(toujours|jamais|absolument|sans aucun doute|il est certain|"
        r"always|never|absolutely|without doubt|it is certain|undeniably|"
        r"unquestionably|definitively)\b",
        re.IGNORECASE,
    )
    _DET_HEDGING = re.compile(
        r"\b(peut-être|il semblerait|on pourrait dire|dans une certaine mesure|"
        r"perhaps|it seems|one could argue|to some extent|arguably|"
        r"it is worth considering|it may be)\b",
        re.IGNORECASE,
    )

    # Remplacements neutres pour chaque groupe (ne tombent PAS dans les listes du détecteur)
    _MARKER_REPLACEMENTS: dict[str, list[str]] = {
        "tout d'abord":          ["d'abord", "pour commencer", "en premier"],
        "premièrement":          ["d'abord", "avant tout"],
        "deuxièmement":          ["ensuite", "puis"],
        "troisièmement":         ["enfin", "pour finir"],
        "en premier lieu":       ["d'abord", "avant tout"],
        "en second lieu":        ["ensuite", "après ça"],
        "en conclusion":         ["bref", "au final", "voilà"],
        "pour conclure":         ["bref", "en fin de compte"],
        "en résumé":             ["bref", "en gros"],
        "en somme":              ["bref", "au total"],
        "il convient de":        ["il faut", "on doit", "mieux vaut"],
        "il est important de":   ["il faut", "pensez à", "n'oublions pas de"],
        "il est essentiel de":   ["il faut absolument", "on ne peut pas éviter de"],
        "dans ce contexte":      ["ici", "dans cette situation", "face à ça"],
        "à cet égard":           ["là-dessus", "sur ce point"],
        "à titre d'exemple":     ["par exemple", "prenons le cas de", "comme"],
        "de plus":               ["et", "aussi", "en plus"],
        "par ailleurs":          ["d'un autre côté", "autrement"],
        "en outre":              ["et", "aussi", "en plus"],
        "cependant":             ["mais", "sauf que", "pourtant"],
        "néanmoins":             ["quand même", "malgré ça", "mais"],
        "toutefois":             ["sauf que", "mais bon", "quand même"],
        "en revanche":           ["à l'inverse", "de l'autre côté", "mais"],
        "d'une part":            ["d'un côté"],
        "d'autre part":          ["de l'autre"],
        "quoi qu'il en soit":    ["quoi qu'il en soit", "de toute façon", "peu importe"],
        "très":                  ["assez", "plutôt", "bien"],
        "vraiment":              ["assez", "bien", "franchement"],
        "absolument":            ["tout à fait", "complètement", "oui"],
        "totalement":            ["entièrement", "à fond", "vraiment"],
        "complètement":          ["tout à fait", "à fond"],
        "entièrement":           ["en totalité", "à fond"],
        "particulièrement":      ["surtout", "en particulier"],
        "notamment":             ["surtout", "par exemple", "entre autres"],
        "spécifiquement":        ["en particulier", "surtout", "précisément"],
    }

    # Synonymes variés pour enrichir le vocabulaire (↑ entropie, ↑ CTTR)
    _VOCAB_EXPANSION: list[tuple[str, list[str]]] = [
        (r"\butiliser\b",      ["employer", "recourir à", "se servir de", "mobiliser"]),
        (r"\bfaire\b",         ["réaliser", "effectuer", "mener", "accomplir"]),
        (r"\bvoir\b",          ["observer", "constater", "remarquer", "percevoir"]),
        (r"\bdire\b",          ["affirmer", "souligner", "indiquer", "préciser"]),
        (r"\bdonner\b",        ["fournir", "apporter", "offrir", "procurer"]),
        (r"\bprendre\b",       ["adopter", "saisir", "choisir", "retenir"]),
        (r"\bmettre\b",        ["placer", "poser", "insérer", "disposer"]),
        (r"\bpenser\b",        ["considérer", "estimer", "juger", "croire"]),
        (r"\bsavoir\b",        ["comprendre", "maîtriser", "connaître", "percevoir"]),
        (r"\bvouloir\b",       ["souhaiter", "désirer", "chercher à", "aspirer à"]),
        (r"\bpouvoir\b",       ["être en mesure de", "avoir la possibilité de", "réussir à"]),
        (r"\bdevenir\b",       ["se transformer en", "évoluer vers", "se muer en"]),
        (r"\bimportant\b",     ["significatif", "notable", "non négligeable", "conséquent"]),
        (r"\bproblème\b",      ["difficulté", "défi", "point délicat", "écueil"]),
        (r"\bsolution\b",      ["réponse", "issue", "moyen", "piste"]),
        (r"\bsystème\b",       ["mécanisme", "dispositif", "ensemble", "structure"]),
        (r"\bprocessus\b",     ["démarche", "procédé", "cheminement", "enchaînement"]),
        (r"\brésultat\b",      ["effet", "conséquence", "aboutissement", "issue"]),
        (r"\baspect\b",        ["dimension", "facette", "angle", "volet"]),
        (r"\bdomaine\b",       ["secteur", "champ", "territoire", "sphère"]),
        (r"\bniveau\b",        ["degré", "plan", "palier", "échelon"]),
        (r"\bapproche\b",      ["méthode", "façon de faire", "angle d'attaque", "stratégie"]),
        (r"\bcadre\b",         ["contexte", "environnement", "périmètre", "structure"]),
        (r"\bperspective\b",   ["angle", "point de vue", "vision", "horizon"]),
        (r"\banalyse\b",       ["étude", "examen", "décryptage", "lecture"]),
        (r"\béléments?\b",     ["points", "aspects", "facteurs", "composantes"]),
        (r"\bbeaucoup\b",      ["énormément", "bien des", "nombre de", "une foule de"]),
        (r"\bpeu\b",           ["guère", "à peine", "pas beaucoup de"]),
        (r"\brapidement\b",    ["vite", "sans tarder", "promptement", "en peu de temps"]),
        (r"\bdifficile\b",     ["ardu", "délicat", "complexe", "pas simple"]),
        (r"\bsimple\b",        ["aisé", "accessible", "direct", "sans détour"]),
    ]

    # ── Dimension 6 : supprimer structures IA (poids 0.10) ──────

    def _remove_ai_structure(self, text: str) -> str:
        """Convertit listes/titres Markdown en prose fluide."""
        lines = text.splitlines()
        prose_lines: list[str] = []
        for line in lines:
            line = re.sub(r'^#{1,6}\s+', '', line)          # titres ##
            line = re.sub(r'^\s*[-•*]\s+', '', line)        # puces
            line = re.sub(r'^\s*\d+[.)]\s+', '', line)      # 1. 2. 3.
            line = re.sub(r'\*\*(.*?)\*\*', r'\1', line)    # **gras**
            line = re.sub(r'\*(.*?)\*', r'\1', line)        # *italic*
            if line.strip():
                prose_lines.append(line.strip())
        # Joindre avec une espace (les virgules cassent la phrase trop court)
        joined = ' '.join(prose_lines)
        return re.sub(r' {2,}', ' ', joined).strip()

    # ── Dimension 3 : supprimer marqueurs IA (poids 0.20) ───────

    def _remove_ai_markers(self, text: str) -> str:
        """Remplace marqueurs IA détectés par des variantes neutres."""
        # D'abord les phrases longues du dict
        for phrase, choices in self._MARKER_REPLACEMENTS.items():
            pattern = r'\b' + re.escape(phrase) + r'\b'
            text = re.sub(pattern, lambda _, c=choices: random.choice(c), text, flags=re.IGNORECASE)
        # Puis les regexes larges du détecteur pour ce qui reste
        text = self._DET_AI_MARKERS.sub(lambda m: self._MARKER_REPLACEMENTS.get(
            m.group(0).lower(), [m.group(0)])[0], text)
        return text

    def _reduce_tone_density(self, text: str) -> str:
        """
        Dimension 8 (poids 0.05) : réduit la densité des mots
        overconfident ET hedging — les deux font monter le score IA.
        """
        # Overconfident → formulations plus nuancées (qui ne sont pas dans la liste)
        overconf_repl = {
            r"\btoujours\b":           ["souvent", "en règle générale", "généralement"],
            r"\bjamais\b":             ["rarement", "quasiment jamais", "très peu"],
            r"\bsans aucun doute\b":   ["assez clairement", "de façon assez évidente"],
            r"\bil est certain\b":     ["il semble", "on peut penser", "il paraît"],
        }
        for pat, choices in overconf_repl.items():
            text = re.sub(pat, lambda _, c=choices: random.choice(c), text, flags=re.I)

        # Hedging → affirmations directes
        hedge_repl = {
            r"\bpeut-être\b":              ["probablement", "sans doute"],
            r"\bil semblerait\b":          ["il semble", "on constate que"],
            r"\bon pourrait dire\b":       ["on dit", "on considère"],
            r"\bdans une certaine mesure\b": ["en partie", "assez largement"],
        }
        for pat, choices in hedge_repl.items():
            text = re.sub(pat, lambda _, c=choices: random.choice(c), text, flags=re.I)
        return text

    # ── Dimensions 1 & 5 : enrichir le vocabulaire ──────────────
    #    Perplexité lex. (0.20) = entropie Shannon → plus de types uniques
    #    Diversité lexicale (0.10) = CTTR = types / √(2×tokens)

    def _enrich_vocabulary(self, text: str, rate: float = 0.45) -> str:
        """
        Remplace aléatoirement des mots courants par des synonymes variés.
        Augmente simultanément l'entropie (perplexité) et le CTTR.
        """
        for pattern, choices in self._VOCAB_EXPANSION:
            def _repl(m: re.Match, c: list[str] = choices) -> str:
                if random.random() > rate:
                    return m.group(0)
                repl = random.choice(c)
                return repl[0].upper() + repl[1:] if m.group(0)[0].isupper() else repl
            text = re.sub(pattern, _repl, text, flags=re.IGNORECASE)
        return text

    # ── Dimensions 2 & 7 : varier la structure des phrases ──────
    #    Uniformité (0.15) = CV des longueurs → CV élevé = humain
    #    Burstiness (0.10) = Gini des longueurs → Gini élevé = humain

    def _split_sentences(self, text: str) -> list[str]:
        parts = re.split(r'(?<=[.!?…])\s+', text)
        return [p.strip() for p in parts if p.strip()]

    def _maximize_burstiness(self, sentences: list[str]) -> list[str]:
        """
        Crée une distribution très inégale des longueurs (Gini élevé) :
        - Coupe les phrases longues (> 20 mots) → 2 phrases courtes
        - Fusionne des paires de phrases très courtes (< 5 mots)
        - Insère des phrases ultra-courtes (3-5 mots) toutes les 3-4 phrases
        """
        result: list[str] = []
        i = 0
        insert_short_every = random.randint(3, 5)

        while i < len(sentences):
            s = sentences[i]
            words = s.split()
            n = len(words)

            # Couper les longues (> 20 mots)
            if n > 20 and random.random() < 0.75:
                # Cherche une virgule proche du milieu
                mid = n // 2
                cut = mid
                for k in range(max(1, mid - 4), min(n - 1, mid + 5)):
                    if words[k].endswith(','):
                        cut = k + 1
                        break
                part1 = " ".join(words[:cut]).rstrip(',') + "."
                part2 = " ".join(words[cut:])
                if part2 and part2[0].islower():
                    part2 = part2[0].upper() + part2[1:]
                result.append(part1)
                if part2.strip():
                    result.append(part2)
                i += 1
                continue

            # Fusionner deux phrases ultra-courtes consécutives (< 5 mots chacune)
            if (n < 5 and i + 1 < len(sentences)
                    and len(sentences[i + 1].split()) < 5):
                glue = random.choice([", et ", " — et pourtant ", ", donc "])
                merged = s.rstrip('.!?') + glue + sentences[i + 1][0].lower() + sentences[i + 1][1:]
                result.append(merged)
                i += 2
                continue

            result.append(s)

            # Insérer une phrase très courte périodiquement
            if (len(result) % insert_short_every == 0
                    and i < len(sentences) - 1):
                shorts = [
                    "C'est clair.", "Pas anodin.", "Ça compte.",
                    "Simple, non ?", "Et c'est tout.", "Voilà l'idée.",
                    "On y reviendra.", "À noter.", "Pas si simple.",
                    "C'est là le nœud.", "Ça mérite réflexion.",
                ]
                result.append(random.choice(shorts))
                insert_short_every = random.randint(3, 5)  # varier le rythme

            i += 1

        return result

    # ── Dimension 4 : richesse ponctuation (poids 0.10) ─────────
    #    Détecteur cherche : [—–…]|\.{3}|!{2,}|\?{2,}
    #    Score IA élevé si densité BASSE → on doit en injecter

    def _inject_human_punctuation(self, sentences: list[str]) -> list[str]:
        """
        Injecte tirets cadratins, ellipses, et doubles ponctuations
        — exactement ce que le détecteur compte comme signes humains.
        """
        result: list[str] = []
        for s in sentences:
            r = random.random()
            if r < 0.18:
                # Remplacer un point par une ellipse en fin de phrase
                s = re.sub(r'\.$', '…', s)
            elif r < 0.30:
                # Insérer un tiret cadratin au milieu d'une phrase longue
                words = s.split()
                if len(words) > 6:
                    pos = random.randint(len(words) // 3, 2 * len(words) // 3)
                    words.insert(pos, '—')
                    s = " ".join(words)
            elif r < 0.36:
                # Double point d'exclamation sur les affirmations fortes
                if s.endswith('.') and any(
                    w in s.lower() for w in ['incroyable', 'essentiel', 'crucial', 'remarquable', 'évident']
                ):
                    s = s[:-1] + '!!'
            result.append(s)
        return result

    # ── Pipeline complet ─────────────────────────────────────────

    def _humanize_core(self, text: str, strength: float = 0.5) -> str:
        """
        Pipeline qui attaque toutes les dimensions dans l'ordre optimal.
        strength ∈ [0.2, 0.9] contrôle l'agressivité globale.
        """
        # 1. Supprimer la structure IA (dim 6, poids 0.10)
        text = self._remove_ai_structure(text)

        # 2. Supprimer marqueurs IA (dim 3, poids 0.20 — poids le plus haut avec perplexité)
        text = self._remove_ai_markers(text)

        # 3. Réduire le ton assertif/prudent (dim 8, poids 0.05)
        text = self._reduce_tone_density(text)

        # 4. Enrichir le vocabulaire (dims 1 + 5, poids 0.30 cumulé)
        text = self._enrich_vocabulary(text, rate=strength * 0.8)

        # 5. Varier la structure des phrases (dims 2 + 7, poids 0.25 cumulé)
        sentences = self._split_sentences(text)
        sentences = self._maximize_burstiness(sentences)

        # 6. Injecter ponctuation humaine (dim 4, poids 0.10)
        sentences = self._inject_human_punctuation(sentences)

        # 7. Recomposer + nettoyer
        text = " ".join(sentences)
        text = re.sub(r' ([,;:.!?…])', r'\1', text)   # espaces avant ponctuation
        text = re.sub(r' {2,}', ' ', text)             # espaces multiples
        text = re.sub(r'\s*—\s*', ' — ', text)         # tirets bien espacés
        return text.strip()

    # ── Styles exposés (chacun appelle _humanize_core) ──────────

    def _human_subtle(self, text: str) -> str:
        """Léger : modifications discrètes, texte proche de l'original."""
        return self._humanize_core(text, strength=0.25)

    def _human_strong(self, text: str) -> str:
        """Fort : transformations marquées sur toutes les dimensions."""
        return self._humanize_core(text, strength=0.60)

    def _human_extreme(self, text: str) -> str:
        """Extrême : réécriture maximale + mélange des phrases."""
        text = self._humanize_core(text, strength=0.85)
        sentences = self._split_sentences(text)
        if len(sentences) > 4:
            core = sentences[1:-1]
            random.shuffle(core)
            sentences = [sentences[0]] + core + [sentences[-1]]
        return " ".join(sentences)

    def _human_stealth(self, text: str) -> str:
        """
        Mode furtif : optimisé pour tromper les détecteurs.
        Pipeline complet + micro-fragments très courts pour
        maximiser le Gini (burstiness) et la variance CV.
        """
        text = self._humanize_core(text, strength=0.70)
        sentences = self._split_sentences(text)
        out: list[str] = []
        for s in sentences:
            out.append(s)
            if random.random() < 0.35:
                ultra_short = [
                    "Voilà.", "C'est dit.", "Pas moins.", "Ça, c'est sûr.",
                    "Simple.", "Net.", "Difficile à nier.", "Parlant.",
                ]
                out.append(random.choice(ultra_short))
        return " ".join(out)

    def _human_student(self, text: str) -> str:
        """Style étudiant : registre familier en plus du pipeline."""
        text = self._humanize_core(text, strength=0.50)
        colloquial = {
            r"\bpar conséquent\b": ["du coup", "donc voilà", "résultat"],
            r"\bainsi\b":          ["du coup", "donc", "bref"],
            r"\bimportant\b":      ["vraiment clé", "pas à négliger", "à retenir"],
            r"\bdifficile\b":      ["pas évident", "galère", "compliqué"],
            r"\bsimple\b":         ["basique", "pas compliqué", "facile"],
        }
        for pat, choices in colloquial.items():
            text = re.sub(pat, lambda _, c=choices: random.choice(c), text, flags=re.I)
        return text

    def _human_pro(self, text: str) -> str:
        """Style professionnel : pipeline + vocabulaire précis."""
        text = self._humanize_core(text, strength=0.35)
        pro = {
            r"\bfaire\b":   ["mettre en œuvre", "conduire", "déployer"],
            r"\bdonner\b":  ["fournir", "apporter", "offrir"],
            r"\bavoir\b":   ["disposer de", "bénéficier de", "posséder"],
        }
        for pat, choices in pro.items():
            text = re.sub(pat, lambda _, c=choices: random.choice(c), text, flags=re.I)
        return text

    def _human_academic(self, text: str) -> str:
        """Style académique : pipeline + propositions subordonnées."""
        text = self._humanize_core(text, strength=0.40)
        sentences = self._split_sentences(text)
        out: list[str] = []
        for s in sentences:
            if random.random() < 0.30 and len(s.split()) > 7:
                subs = [
                    "ce qui soulève la question de",
                    "bien que cela mérite nuance",
                    "dès lors qu'on l'examine attentivement",
                    "à condition de contextualiser",
                ]
                s = s.rstrip('.!?') + ", " + random.choice(subs) + "."
            out.append(s)
        return " ".join(out)

    def _human_journalistic_advanced(self, text: str) -> str:
        """Style journalistique : pipeline + phrases courtes percutantes."""
        text = self._humanize_core(text, strength=0.55)
        sentences = self._split_sentences(text)
        if sentences:
            # Raccourcir la première phrase (accroche)
            w = sentences[0].split()
            if len(w) > 8:
                sentences[0] = " ".join(w[:7]) + "."
        return " ".join(sentences)

    def _human_technical_advanced(self, text: str) -> str:
        """Style technique : pipeline + jargon spécialisé."""
        text = self._humanize_core(text, strength=0.30)
        tech = {
            r"\butilise\b":   ["exploite", "déploie", "implémente"],
            r"\bsystème\b":   ["stack", "infrastructure", "architecture"],
            r"\bprocessus\b": ["pipeline", "workflow", "flux"],
            r"\bfonction\b":  ["méthode", "handler", "routine"],
        }
        for pat, choices in tech.items():
            text = re.sub(pat, lambda _, c=choices: random.choice(c), text, flags=re.I)
        return text

    def _human_scientific(self, text: str) -> str:
        """Style scientifique : pipeline + modalisation des affirmations."""
        text = self._humanize_core(text, strength=0.35)
        modal = {
            r"\bmontre\b":   ["tend à indiquer", "suggère", "laisse supposer"],
            r"\bprouve\b":   ["corrobore", "est cohérent avec", "appuie l'idée que"],
            r"\btoujours\b": ["généralement", "dans la plupart des cas"],
            r"\bjamais\b":   ["rarement", "dans très peu de cas"],
        }
        for pat, choices in modal.items():
            text = re.sub(pat, lambda _, c=choices: random.choice(c), text, flags=re.I)
        return text

    def _human_legal(self, text: str) -> str:
        """Style juridique : pipeline + désignations formelles."""
        text = self._humanize_core(text, strength=0.25)
        legal = {
            r"\bdoit\b":    ["est tenu de", "a l'obligation de"],
            r"\bpeut\b":    ["est habilité à", "a la faculté de"],
            r"\baccord\b":  ["convention", "disposition"],
            r"\brègle\b":   ["norme applicable", "disposition réglementaire"],
        }
        for pat, choices in legal.items():
            text = re.sub(pat, lambda _, c=choices: random.choice(c), text, flags=re.I)
        return text

    def _human_medical(self, text: str) -> str:
        """Style médical : pipeline + vocabulaire clinique."""
        text = self._humanize_core(text, strength=0.30)
        med = {
            r"\bimportant\b":    ["cliniquement significatif", "à surveiller"],
            r"\bmontre\b":       ["objective", "met en évidence"],
            r"\btraitement\b":   ["prise en charge", "protocole thérapeutique"],
            r"\bpatient\b":      ["sujet", "cas clinique", "personne concernée"],
        }
        for pat, choices in med.items():
            text = re.sub(pat, lambda _, c=choices: random.choice(c), text, flags=re.I)
        return text

    def _human_marketing(self, text: str) -> str:
        """Style marketing : pipeline + vocabulaire impact/bénéfice."""
        text = self._humanize_core(text, strength=0.45)
        mkt = {
            r"\bimportant\b":  ["qui fait la différence", "incontournable", "décisif"],
            r"\butiliser\b":   ["profiter de", "exploiter", "tirer parti de"],
            r"\baméliorer\b":  ["booster", "optimiser", "transformer"],
        }
        for pat, choices in mkt.items():
            text = re.sub(pat, lambda _, c=choices: random.choice(c), text, flags=re.I)
        return text

    def _human_historical(self, text: str) -> str:
        """Style historique : pipeline + mise en perspective temporelle."""
        text = self._humanize_core(text, strength=0.30)
        if text and text[0].isupper():
            text = "À cette époque, " + text[0].lower() + text[1:]
        return text

    def _human_philosophical(self, text: str) -> str:
        """Style philosophique : pipeline + questionnement final."""
        text = self._humanize_core(text, strength=0.35)
        sentences = self._split_sentences(text)
        if sentences:
            tail = [
                "mais n'est-ce pas là toute la question ?",
                "— à moins que ce ne soit l'inverse.",
                "ce qui reste, en fin de compte, ouvert.",
            ]
            sentences[-1] = sentences[-1].rstrip('.!?') + " — " + random.choice(tail)
        return " ".join(sentences)

    def _human_educational(self, text: str) -> str:
        """Style éducatif : pipeline + structuration pédagogique."""
        text = self._humanize_core(text, strength=0.30)
        sentences = self._split_sentences(text)
        out: list[str] = []
        for i, s in enumerate(sentences):
            out.append(s)
            if i == 0 and random.random() < 0.5:
                out.append("Voyons ça de plus près.")
        return " ".join(out)

    def _human_targeted(self, text: str, mode: str = "subtil") -> str:
        """Dispatche vers le style demandé."""
        dispatch = {
            "subtil":       self._human_subtle,
            "fort":         self._human_strong,
            "extreme":      self._human_extreme,
            "furtif":       self._human_stealth,
            "etudiant":     self._human_student,
            "pro":          self._human_pro,
            "academique":   self._human_academic,
            "journaliste":  self._human_journalistic_advanced,
            "technique":    self._human_technical_advanced,
            "scientifique": self._human_scientific,
            "juridique":    self._human_legal,
            "medical":      self._human_medical,
            "marketing":    self._human_marketing,
            "historique":   self._human_historical,
            "philo":        self._human_philosophical,
            "educatif":     self._human_educational,
        }
        return dispatch.get(mode.lower(), self._human_subtle)(text)


    # ============================================================
    #  *** Fonctions d'exécution du service (API) ***
    # ============================================================

    def humanize(self, file_path: Path, mode: str="subtil") -> bool:
        """Point d'entrée principal pour humaniser un fichier."""
        print(f"\n[HUMANISATION] Démarrage du nettoyage de {file_path} dans le mode : {mode.upper()}")
        try:
            # 1. Lecture brute (Assure que l'on copie le contenu, jamais en place)
            with open(str(file_path), 'r', encoding='utf-8', errors='ignore') as f:
                text = f.read()
            
            # 2. Transformation
            humanized_text = self._human_targeted(text, mode) 
            
            # 3. Écrasement du fichier original (écriture en place garantie de la modifcation)
            with open(str(file_path), 'w', encoding='utf-8') as f:
                f.write(humanized_text)
            print(f"[SUCCÈS] Le fichier a été modifié et sauvegardé.")
            return True

        except Exception as e:
             print(f" [ERREUR] Échec de l'humanisation du contenu : {type(e).__name__}: {e}")
             return False


    def humanize_batch(self, file_paths: list[Path], mode: str = "subtil") -> list[tuple[str, bool]]:
        """Humanise plusieurs fichiers avec le même mode."""
        results = []
        for file_path in file_paths:
            if self.humanize(file_path, mode):
                results.append((str(file_path), True))
            else:
                results.append((str(file_path), False))
        return results

    def humanize_directory(self, directory_path: str, mode: str = "subtil", recursive: bool = True) -> list[tuple[str, Path]]:
        """Humanise tous les fichiers dans un répertoire."""
        if not os.path.exists(directory_path):
            print(f" [ERREUR] Le répertoire n'existe pas: {directory_path}")
            return []
        
        print(f"\n[BATCH HUMANIZATION] Démarrage pour le répertoire: {directory_path} (mode: {mode})")
        results = []
        for root, dirs, files in os.walk(directory_path):
            for filename in files:
                file_path = Path(os.path.join(root, filename))
                ext = file_path.suffix.lower()
                if ext in self.text_extensions:
                    self.humanize(file_path, mode) 
                    results.append((str(file_path), file_path))
        return results